theme: jekyll-theme-minimal
title: Voice Apps - Ausstellung der Studierenden des Bachelorstudiengangs Informatik und Design
description: Hi!A - Festival für Kunst und Forschung in Bayern 
show_downloads: false
logo: "/assets/img/hia.png"
favicon: true
